### ISSUE TITLE
Hi, questions about pre-training  of C2FTrans

### ISSUE THREAD

**Issue by weiaicunzai** [xianlin7/BATFormer#1]
Hi, thanks for sharing your code. I have a question about the pre-training of C2FTrans.  I would like to know if the results in the paper were trained from scratch or pre-trained on other datasets since there are no details on pre-training C2FTrans in the paper. Could you please let me know which datasets you used if the model was pre-trained on the other datasets? Thanks.

**Comment by xianlin7** [comment]
Thanks for your interest. The model was trained from scratch in our experiments.

**Comment by weiaicunzai** [comment]
> Hi, thanks for sharing your code. I have a question about the pre-training of C2FTrans. I would like to know if the results in the paper were trained from scratch or pre-trained on other datasets since there are no details on pre-training C2FTrans in the paper. Could you please let me know which datasets you used if the model was pre-trained on the other datasets? Thanks.

Thanks for your reply. Given the small size of the dataset (e.g. Glas dataset), it is impressive.
