### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by Moonlongnight** [xianlin7/BATFormer#2]
If I test the ACDC dataset, how should I set the folder and image format? Hope to get an answer soon. Thanks.

**Comment by xianlin7** [comment]
A VOC dataset type is OK. For example:
--ACDC
        --img
                --patient001_frame01_001.png (or .nii.gz)
        --label
        --MainPatient
                --train.txt
                --val.txt
                --test.txt
As our model is based on 2D, the 3D input of the ACDC dataset should be preprocessed into 2D slices first.

**Comment by xianlin7** [comment]
A VOC dataset type is OK. For example:
`
--ACDC
      --img
               --patient001_frame01_001.png (or .nii.gz)
      --label
      --MainPatient
                --train.txt
                --val.txt
                --test.txt
`
As our model is based on 2D, the 3D input of the ACDC dataset should be preprocessed into 2D slices first.

**Comment by xianlin7** [comment]
A VOC dataset type is OK. For example:
--ACDC 
----------img 
------------------patient001_frame01_001.png (or .nii.gz) 
----------label
----------MainPatient
------------------train.txt 
------------------val.txt 
------------------test.txt
As our model is based on 2D, the 3D input of the ACDC dataset should be preprocessed into 2D slices first.

**Comment by Moonlongnight** [comment]
> A VOC dataset type is OK. For example: --ACDC ----------img ------------------patient001_frame01_001.png (or .nii.gz) ----------label ----------MainPatient ------------------train.txt ------------------val.txt ------------------test.txt As our model is based on 2D, the 3D input of the ACDC dataset should be preprocessed into 2D slices first.

Thank you very much for your reply，Can I request your preprocessed ACDC dataset for experimentation? If possible, I hope to contact my Email: 976037282@qq.com

**Comment by xianlin7** [comment]
Sure, I've emailed you.

**Comment by Moonlongnight** [comment]
Thank you so much! We commit to using it for research purposes and do not redistribute it. If we produce results, your contribution will be cited by us

**Comment by xianlin7** [comment]
Good Luck :)

**Comment by AasiaRehman** [comment]
How to use the code for ISIC2018. I mean what changes need to be done in train and test code

**Comment by xianlin7** [comment]
You can change the path of the dataset, the number of classes, the image size of your dataset, the grey of your dataset, and the eval mode.
--dataset         -> ISIC
--classes          -> 2
--imgsize         -> 256/512
--gray              -> no
--eval_mode    -> slice
 Other hyper-parameters can be changed as you like.

**Comment by AasiaRehman** [comment]
Thank You so much for the information
can you help me in this error

Traceback (most recent call last):
  File "/content/drive/MyDrive/My Drive/C2FTrans-main/train.py", line
79, in <module>
    train_dataset = ImageToImage2D(args.dataset, 'train', tf_train,
args.classes)  # only random horizontal flip, return image, mask, and
filename
  File "/content/drive/MyDrive/My
Drive/C2FTrans-main/utils/utils_multi_rgb.py", line 266, in __init__
    self.ids = [id_.strip() for id_ in open(id_list_file)]
FileNotFoundError: [Errno 2] No such file or directory:
'/content/drive/MyDrive/My Drive/ISIC2018_256/MainPatient/train.txt'



Do I need to make list of filenames??

*With Regards,*
*Aasia Rehman *
*Research Scholar*
*University of Kashmir*
