### ISSUE TITLE
Request your preprocessed ACDC dataset to repeat your experimentation

### ISSUE THREAD

**Issue by NickWang1122** [xianlin7/BATFormer#3]
Could I get your preprocessed ACDC dataset? If possible, I hope to contact my Email: 931072370@qq.com.Looking forward to your reply.

**Comment by xianlin7** [comment]
Sure, I've emailed you.

**Comment by NickWang1122** [comment]
Thank you very much for sharing！

**Comment by NickWang1122** [comment]
> Sure, I've emailed you.

Thank you very much for sharing！

**Comment by GuoQingqing** [comment]
> Sure, I've emailed you.

Could you please send the preprocessed ACDC dataset to me? My Email: 1605754116@qq.com. Thank you very much!

**Comment by Snowwwwwwwwwww** [comment]
Could you please send the preprocessed ACDC dataset to me? My Email: [2432584038@qq.com]. Thank you very much!

**Comment by beihaiyou** [comment]
Could you please send the preprocessed ACDC dataset to me? My Email: [[1362770093@qq.com](mailto:1362770093@qq.com)]. Thank you very much!

**Comment by xianlin7** [comment]
> > Sure, I've emailed you.
> 
> Could you please send the preprocessed ACDC dataset to me? My Email: [1605754116@qq.com](mailto:1605754116@qq.com). Thank you very much!
We have publicly released the preprocessed ACDC dataset.
You can download it from here https://drive.google.com/file/d/18W_d8ho0Tl7TgPQXczOXZK5OUxtYkQdc/view?usp=share_link.

**Comment by xianlin7** [comment]
> Could you please send the preprocessed ACDC dataset to me? My Email: [[2432584038@qq.com](mailto:2432584038@qq.com)]. Thank you very much!

We have publicly released the preprocessed ACDC dataset.
You can download it from here https://drive.google.com/file/d/18W_d8ho0Tl7TgPQXczOXZK5OUxtYkQdc/view?usp=share_link.

**Comment by xianlin7** [comment]
> Could you please send the preprocessed ACDC dataset to me? My Email: [[1362770093@qq.com](mailto:1362770093@qq.com)]. Thank you very much!

We have publicly released the preprocessed ACDC dataset.
You can download it from here https://drive.google.com/file/d/18W_d8ho0Tl7TgPQXczOXZK5OUxtYkQdc/view?usp=share_link.
