### ISSUE TITLE
C2FTrans

### ISSUE THREAD

**Issue by cxz0101** [xianlin7/BATFormer#4]
这个项目是C2FTrans的代码还是BATFormer。我看到项目里面的是C2FTrans。我的猜想是C2FTrans=BATFormer。可以这样理解嘛，谢谢

**Comment by xianlin7** [comment]
是的，调整了下名字，但是arXiv还没有同步更新

**Comment by wqw123wqw** [comment]
![image](https://user-images.githubusercontent.com/81298794/204068057-f03c0ae5-962a-4317-8060-5a60faa1cd48.png)
为什么这个代码训练的时候，train loss 反而有上升的趋势

**Comment by xianlin7** [comment]
我们没有遇到过这个情况，你可以检查下你的数据集和标签是否一一对应。
